ktor {
  development = true

  deployment {
    port = ${PORT:8080}
    host = "0.0.0.0"
  }

  application {
    modules = [ com.vindev.pvpguide.ApplicationKt.module ]
  }
}

app {
  name = "PvP Guide Backend"

  api {
    basePath = "/api"
  }

  cors {
    # Hosts only, no http:// or https:// here
    hosts = [ "localhost:3000", "localhost:5173", "127.0.0.1:3000", "127.0.0.1:5173" ]

    # Usually just http for local dev
    schemes = [ "http" ]

    allowCredentials = false
  }
}